version: "3.4"

services:
  php:
    container_name: ${APP_NAME}_php
    build:
      context: .
      dockerfile: Dockerfile-php
      args:
        SYMFONY_VERSION: ${SYMFONY_VERSION:-}
        STABILITY: ${STABILITY:-stable}
        GITHUB_USER_NAME: ${GITHUB_USER_NAME:-}
        GITHUB_USER_EMAIL: ${GITHUB_USER_EMAIL:-}
    restart: unless-stopped
    volumes:
      - "./php_socket:/var/www/symfony"
    healthcheck:
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 30s
    environment:
      # Run "composer require symfony/orm-pack" to install and configure Doctrine ORM
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:5432/${POSTGRES_DB}?serverVersion=${POSTGRES_VERSION:-14}
    networks:
      symfony_net:
        ipv4_address: 172.20.0.2

  nginx:
    container_name: ${APP_NAME}_nginx
    depends_on:
      - php
    build:
      context: .
      dockerfile: Dockerfile-nginx
    ports:
      - 4444:80
      - 4443:443
    volumes:
      - "/php_socket:/var/www/symfony"
    networks:
      symfony_net:
        ipv4_address: 172.20.0.3

networks:
  symfony_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

volumes:
  php_socket:
#    driver: local
#    driver_opts:
#      type: 'none'
#      o: 'bind'
#      device: ${PATH_TO_PROJECT}/php_socket
